import os
import zipfile
from io import BytesIO
import streamlit as st
from google import genai
from google.genai import types
from dotenv import load_dotenv

load_dotenv()

# Gemini API Code Generation with proper safety checks
def generate_full_app_code(prompt, language):
    client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
    model = "gemini-2.5-flash"
    contents = [
        types.Content(
            role="user",
            parts=[types.Part.from_text(text=f"Generate a full production-ready {language} application project based on this description: {prompt}. Include all necessary files, Docker configuration, tests, and deployment scripts.")],
        )
    ]
    generate_content_config = types.GenerateContentConfig(
        temperature=1,
        max_output_tokens=65535,
        thinking_config=types.ThinkingConfig(thinking_budget=0),
    )
    
    full_code = ""
    for chunk in client.models.generate_content_stream(
        model=model,
        contents=contents,
        config=generate_content_config,
    ):
        if chunk.text:
            full_code += chunk.text
    return full_code

# ZIP the generated code into a downloadable package
def create_zip_from_code(code_text):
    zip_buffer = BytesIO()
    with zipfile.ZipFile(zip_buffer, 'w') as zip_file:
        zip_file.writestr("project_generated/README.md", "# Generated Application\nThis project was generated by Gemini API.")
        zip_file.writestr("project_generated/app_description.txt", code_text)
        zip_file.writestr("project_generated/Dockerfile", """
# Example Dockerfile
FROM python:3.9-slim
WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt
CMD ["python", "main.py"]
        """)
    zip_buffer.seek(0)
    return zip_buffer

# Extract uploaded ZIP file safely
def handle_zip_upload(uploaded_file):
    upload_dir = "uploaded_files"
    os.makedirs(upload_dir, exist_ok=True)

    with zipfile.ZipFile(uploaded_file, 'r') as zip_ref:
        zip_ref.extractall(upload_dir)
    
    return upload_dir

# Streamlit chatbot interface
def main():
    st.set_page_config(page_title="Gemini App Generator", layout="wide")

    st.title("🚀 Gemini-Powered End-to-End Application Generator Chatbot")

    language = st.selectbox(
        "Select Target Programming Language",
        ["Python", "TypeScript", "Java", "C++", "Ruby"]
    )

    user_prompt = st.text_area(
        "Describe your full application requirement in detail (be as specific as possible):",
        height=200
    )

    if st.button("💡 Generate Full App Code"):
        if not user_prompt.strip():
            st.error("⚠️ Please provide a description of your application.")
            return

        with st.spinner("⏳ Generating full production-ready code (this may take a few minutes)..."):
            try:
                generated_code = generate_full_app_code(user_prompt, language)
                
                st.subheader("✅ Generated Application Code Preview:")
                st.code(generated_code, language="python")

                zip_file = create_zip_from_code(generated_code)

                st.download_button(
                    label="📥 Download Complete Application as ZIP",
                    data=zip_file,
                    file_name="generated_app.zip",
                    mime="application/zip"
                )
                st.success("🎉 Application generated successfully!")
            except Exception as e:
                st.error(f"⚠️ An error occurred during generation: {str(e)}")

    st.markdown("---")

    uploaded_file = st.file_uploader("📂 Upload existing project ZIP (Optional)", type="zip")
    if uploaded_file:
        try:
            extracted_path = handle_zip_upload(uploaded_file)
            st.success(f"✅ Uploaded and extracted files available at: `{extracted_path}`")
        except Exception as e:
            st.error(f"⚠️ Failed to extract ZIP: {str(e)}")

if __name__ == "__main__":
    main()
