import os
import zipfile
import base64
from io import BytesIO
import streamlit as st
from google import genai
from google.genai import types
from dotenv import load_dotenv

load_dotenv()

# Gemini API Code Generation
def generate_full_app_code(prompt, language):
    client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
    model = "gemini-2.5-flash"
    contents = [
        types.Content(
            role="user",
            parts=[types.Part.from_text(text=f"Generate a full production-ready {language} application project based on this description: {prompt}. Include all necessary files, Docker configuration, tests, and deployment scripts.")],
        )
    ]
    generate_content_config = types.GenerateContentConfig(
        temperature=1,
        max_output_tokens=65535,
        thinking_config=types.ThinkingConfig(thinking_budget=0),
    )
    
    full_code = ""
    for chunk in client.models.generate_content_stream(
        model=model,
        contents=contents,
        config=generate_content_config,
    ):
        full_code += chunk.text
    return full_code

# ZIP generated code for download
def create_zip_from_code(code_text):
    zip_buffer = BytesIO()
    with zipfile.ZipFile(zip_buffer, 'w') as zip_file:
        zip_file.writestr("project_generated/README.md", "# Generated Application\nThis project was generated by Gemini API.")
        zip_file.writestr("project_generated/app_description.txt", code_text)
        zip_file.writestr("project_generated/Dockerfile", """
# Example Dockerfile
FROM python:3.9-slim
WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt
CMD ["python", "main.py"]
        """)
    zip_buffer.seek(0)
    return zip_buffer

# Handle file upload and extraction
def handle_zip_upload(uploaded_file):
    with zipfile.ZipFile(uploaded_file, 'r') as zip_ref:
        zip_ref.extractall("uploaded_files")
    return "uploaded_files"

# Streamlit chatbot UI
def main():
    st.title("🚀 Gemini-Powered End-to-End Application Generator Chatbot")

    language = st.selectbox("Select Language", ["Python", "typeScript", "Java", "C++", "Ruby"])
    user_prompt = st.text_area("Describe your full application requirement in detail:", height=200)

    if st.button("Generate Full App Code"):
        if not user_prompt.strip():
            st.error("Please provide a description of your application.")
            return

        with st.spinner("Generating full production-ready code... This may take a while..."):
            generated_code = generate_full_app_code(user_prompt, language)
            st.code(generated_code, language="python")

            zip_file = create_zip_from_code(generated_code)

            st.download_button(
                label="📥 Download Complete Application as ZIP",
                data=zip_file,
                file_name="generated_app.zip",
                mime="application/zip"
            )
            st.success("Full application generated successfully.")

    uploaded_file = st.file_uploader("Or upload existing project ZIP", type="zip")
    if uploaded_file:
        extracted_path = handle_zip_upload(uploaded_file)
        st.success(f"Uploaded and extracted files to {extracted_path}")

if __name__ == "__main__":
    main()
